### ISSUE TITLE
Zram size is too small

### ISSUE THREAD

**Issue by FreeLife2** [Official-Ayrton990/android_kernel_xiaomi_sm8250#9] opened 2022-06-01 01:06 UTC
Can user space be allowed to set zram size? In version r6.6, zram is forced to be locked at 2GB, which is too small for some ROMs. Thank you

**Comment by Official-Ayrton990** [comment] 2022-06-01 03:00
> Can user space be allowed to set zram size? In version r6.6, zram is forced to be locked at 2GB, which is too small for some ROMs. Thank you

This can be allowed, but what is your reason to think some roms needs to increase it? the issue is that you will waist more cpu cycles on decompression tasks.

**Comment by Official-Ayrton990** [comment] 2022-06-01 03:20
This should be enough for your request: https://github.com/Official-Ayrton990/android_kernel_xiaomi_sm8250/commit/caa65070d5156e5dfa3cc0a6ffa2658d7454edb2

Closing the issue but with a remark that this is just a request.

**Closed as completed by Official-Ayrton990** 2022-06-01 03:20 UTC
